### ISSUE TITLE
Can't remove items from "Exclude from Source" list

### ISSUE THREAD

**Issue by HunterZ** [Remod-org/NextGenPVE#8]
Using versions 1.6.8 & 1.6.9 with Carbon, I can add items to the "Exclude from Source" list, but I can't remove them. Nothing shows up green in the pick list.

Edit: Chat commands for this don't work either - they just bring up the GUI?

DB Browser for SQLite is able to read/modify the database though if I'm that desperate lol.

**Comment by RFC1920** [comment]
It's possible that the commands do not just work as you might expect since they were pretty much designed for the GUI.  The GUI has to use commands, so...

I don't know what's special about Carbon here.  You might try saving your database and starting fresh to see if the behavior is the same.  There could be some duplicate default rulesets causing issues here.  Sorry, but I am not setup to test with Carbon.  I only know it is working with Oxide.

**Comment by HunterZ** [comment]
> It's possible that the commands do not just work as you might expect since they were pretty much designed for the GUI. The GUI has to use commands, so...

I'm saying that I can't remove items from the "Exclude from Source" list via the GUI *or* via commands.

Once I add them, they're stuck in the list forever.

> I don't know what's special about Carbon here. You might try saving your database and starting fresh to see if the behavior is the same. There could be some duplicate default rulesets causing issues here. Sorry, but I am not setup to test with Carbon. I only know it is working with Oxide.

I did try wiping my config multiple times and starting completely fresh just in case, and it's repeatable.

I've swapped out NextGenPVE for TruePVE for now, and other than the burden of having to set up / maintain entity groups it seems a lot more intuitive to configure so far.

**Comment by Owned67** [comment]
hello, not using carbon but same problem... latest oxide and server...
